### ISSUE TITLE
Failed to do `cargo build --release` for 0.9.0 and HEAD with rust 1.72.0

### ISSUE THREAD

**Issue by chenrui333** [kpcyrd/sh4d0wup#12] opened 2023-08-27 18:14 UTC
👋 while trying to upgrade rust to 1.72.0, we ran into the stuck build with yash-syntax crate.

While `cargo build` works fine, but it failed with `cargo build --release`

![image](https://github.com/kpcyrd/sh4d0wup/assets/1580956/9d176e8f-ccce-4cea-8a11-71081026ab57)

rustc --crate-name yash_syntax --edition=2021 /Users/rui/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yash-syntax-0.6.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=155 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=64d2c0b358580c39 -C extra-filename=-64d2c0b358580c39 --out-dir /Users/rui/Downloads/brew/sh4d0wup/target/release/deps -L dependency=/Users/rui/Downloads/brew/sh4d0wup/target/release/deps --extern async_trait=/Users/rui/Downloads/brew/sh4d0wup/target/release/deps/libasync_trait-37f75ec5eb81b709.dylib --extern futures_util=/Users/rui/Downloads/brew/sh4d0wup/target/release/deps/libfutures_util-a79f4b19fb62844a.rmeta --extern itertools=/Users/rui/Downloads/brew/sh4d0wup/target/release/deps/libitertools-e862d6f649772b8b.rmeta --cap-lints allow

relates to https://github.com/Homebrew/homebrew-core/pull/140367

**Comment by kpcyrd** [comment] 2023-08-27 22:16
I can reproduce this, I suspect this is a compiler regression related to "[Const evaluation time is now unlimited](https://blog.rust-lang.org/2023/08/24/Rust-1.72.0.html#const-evaluation-time-is-now-unlimited)", I managed to work around this by adding this to my Cargo.toml (https://github.com/kpcyrd/sh4d0wup/commit/594e55c81b2f3e7e329f2061f9ce8a23750164da):

```toml
[profile.release.package.yash-syntax]
opt-level = 0
```

It also seems to be fixed with the current 1.73.0 Rust beta.

Thanks for reporting!

**Comment by ZhongRuoyu** [comment] 2023-08-28 02:59
Thanks @chenrui333 for the report and @kpcyrd for the insight! I can confirm that https://github.com/rust-lang/rust/pull/114948 fixed this issue on Rust's side. With that patch applied to `rustc`, `sh4d0wup` can again be built normally.

**Comment by kpcyrd** [comment] 2023-09-09 14:21
I've released 0.9.1 that contains a workaround.

Thanks for the notification!

**Closed as completed by kpcyrd** 2023-09-09 14:21 UTC
